_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("art_poly_train_rotate_pos",)
  TEST: ("art_test",)

MODEL:
  WEIGHTS: "output/r_50_poly/pretrain_art/model_final.pth"  # or the provided pre-trained model
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.325

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 5e-5
  LR_BACKBONE: 5e-6
  WARMUP_ITERS: 0
  STEPS: (40000,)
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 50000

INPUT:
  MIN_SIZE_TEST: 1200
  MAX_SIZE_TEST: 1900

TEST:
  EVAL_PERIOD: 50000

OUTPUT_DIR: "output/r_50_poly/art/finetune"
